### ISSUE TITLE
Errors after running training.py

### ISSUE THREAD

**Issue by jskDr** [akshaybetala/UG-RNN#1]
I got errors after I ran the following command. How can I resolve this error? This error comes from the invalid use of lan(). 
jamessungjinkim$ python training.py 
Traceback (most recent call last):
  File "training.py", line 24, in <module>
    flags.DEFINE_integer('initial_feature_vector_size',utils.num_of_features(),'Size of the individual feature for all the nodes' )
  File "/home/jamessungjinkim/Dropbox/Aspuru-Guzik/030 Labs/Py3/github_download/Deep-Learning-in-Chemoinformatics/src/utils.py", line 6, in num_of_features
    return num_bond_features()+num_atom_features()
  File "/home/jamessungjinkim/Dropbox/Aspuru-Guzik/030 Labs/Py3/github_download/Deep-Learning-in-Chemoinformatics/src/utils.py", line 62, in num_atom_features
    return len(atom_features(a))
TypeError: len() of unsized object

**Comment by akshaybetala** [comment]
Hi Sungjin,

The project is still ongoing and not complete.

Regards
Akshay

Akshay Jain
Masters in Computer Science
University Of California
+1 949-501-5552
